twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        categories_g: '@App\Repository\CategorieRepository'
        panierService: '@App\Panier\PanierService'

when@test:
    twig:
        strict_variables: true
